title: Binary is better
author: Emanuele Giacomelli
description: Personal notes about my software developer things
baseurl: "/binary-is-better"
url: "https://binary-manu.github.io"
theme: minima
plugins:
    - jekyll-feed
    - jekyll-toc
collections:
    posts:
        output: true
        permalink: :categories/:title
defaults:
    - scope:
          path: ""
          type: posts
      values:
          layout: post
          toc: true
    - scope:
          path: ""
          type: drafts
      values:
          layout: post
          toc: true
exclude:
    - Gemfile
    - Gemfile.lock
    - vendor/
    - rsrc/
toc:
    min_level: 2
    max_level: 4
