title: Binary is better
author: Emanuele Giacomelli
description: Personal notes about my software developer things
baseurl: "/binary-is-better"
url: "https://binary-manu.github.io"
email: "binary-is-better@altmails.com"
theme: minima
plugins:
    - jekyll-feed
collections:
    posts:
        output: true
        permalink: :categories/:title
defaults:
    - scope:
          path: ""
          type: posts
      values:
          layout: post
    - scope:
          path: ""
          type: drafts
      values:
          layout: post
exclude:
    - Gemfile
    - Gemfile.lock
    - vendor/
    - rsrc/
